// Geodesy helpers and the map projection layer.
//
// The map image is generated by tools/generate_map.py, which records its projection in
// map_meta.json. All drawing code goes through makeProjection(), so supporting a
// projection is just an entry here plus the matching inverse in projection_inverse.js.

const EARTH_RADIUS_M = 6378137.0;
export const METERS_PER_MILE = 1609.344;

const rad = (deg) => (deg * Math.PI) / 180;
const deg = (r) => (r * 180) / Math.PI;

export function wrap360(a) {
    return ((a % 360) + 360) % 360;
}

// Shortest signed angular difference a - b, in (-180, 180].
export function angleDiff(a, b) {
    let d = (a - b) % 360;
    if (d <= -180) d += 360;
    if (d > 180) d -= 360;
    return d;
}

export function haversineDistance(lat1, lon1, lat2, lon2) {
    const dLat = rad(lat2 - lat1);
    const dLon = rad(lon2 - lon1);
    const a =
        Math.sin(dLat / 2) ** 2 +
        Math.cos(rad(lat1)) * Math.cos(rad(lat2)) * Math.sin(dLon / 2) ** 2;
    return 2 * EARTH_RADIUS_M * Math.asin(Math.sqrt(a));
}

// Initial great-circle bearing from point 1 toward point 2, degrees clockwise from north.
export function initialBearing(lat1, lon1, lat2, lon2) {
    const p1 = rad(lat1);
    const p2 = rad(lat2);
    const dLon = rad(lon2 - lon1);
    const y = Math.sin(dLon) * Math.cos(p2);
    const x = Math.cos(p1) * Math.sin(p2) - Math.sin(p1) * Math.cos(p2) * Math.cos(dLon);
    return wrap360(deg(Math.atan2(y, x)));
}

// Point reached by following a great circle from (lat, lon) at the given initial bearing
// for the given distance.
export function greatCircleDestination(lat, lon, bearingDeg, distanceM) {
    const delta = distanceM / EARTH_RADIUS_M;
    const theta = rad(bearingDeg);
    const p1 = rad(lat);
    const l1 = rad(lon);
    const p2 = Math.asin(
        Math.sin(p1) * Math.cos(delta) + Math.cos(p1) * Math.sin(delta) * Math.cos(theta),
    );
    const l2 =
        l1 +
        Math.atan2(
            Math.sin(theta) * Math.sin(delta) * Math.cos(p1),
            Math.cos(delta) - Math.sin(p1) * Math.sin(p2),
        );
    return { latitude: deg(p2), longitude: deg(l2) };
}

function mercatorXY(latitude, longitude) {
    return {
        x: EARTH_RADIUS_M * rad(longitude),
        y: EARTH_RADIUS_M * Math.asinh(Math.tan(rad(latitude))),
    };
}

// Build a projection object from map_meta.json. latLonToPixel maps onto the map image's
// own pixel grid (0..image_size_px in both axes, y down); callers scale to their canvas.
export function makeProjection(meta) {
    if (meta.projection === "azimuthal_equidistant") {
        // Polar chart about the dish: pixel radius is exactly proportional to ground
        // range, pixel angle is true bearing. Same spherical earth as the generator, so
        // these pixels land on the features they name.
        const center = meta.image_size_px / 2;
        return {
            latLonToPixel(latitude, longitude) {
                const r =
                    haversineDistance(
                        meta.center_latitude, meta.center_longitude, latitude, longitude,
                    ) / meta.meters_per_pixel;
                const theta = rad(
                    initialBearing(
                        meta.center_latitude, meta.center_longitude, latitude, longitude,
                    ),
                );
                return {
                    x: center + r * Math.sin(theta),
                    y: center - r * Math.cos(theta),
                };
            },
        };
    }
    if (meta.projection === "webmercator") {
        const size = meta.image_size_px;
        const spanX = meta.merc_x_max - meta.merc_x_min;
        const spanY = meta.merc_y_max - meta.merc_y_min;
        return {
            latLonToPixel(latitude, longitude) {
                const m = mercatorXY(latitude, longitude);
                return {
                    x: ((m.x - meta.merc_x_min) / spanX) * size,
                    y: ((meta.merc_y_max - m.y) / spanY) * size,
                };
            },
        };
    }
    throw new Error(`Unsupported map projection "${meta.projection}".`);
}

// Sample the great-circle path leaving the map center at the given azimuth, projected to
// map image pixels. Used to draw azimuth needles that stay honest about projection
// distortion out to the edge of the map: they curve under webmercator, and come out
// collinear (a straight ray) under azimuthal-equidistant, without the caller caring.
export function azimuthPathPixels(meta, projection, azimuthDeg, maxDistanceM, steps = 32) {
    const points = [];
    for (let i = 0; i <= steps; i++) {
        const p = greatCircleDestination(
            meta.center_latitude,
            meta.center_longitude,
            azimuthDeg,
            (maxDistanceM * i) / steps,
        );
        points.push(projection.latLonToPixel(p.latitude, p.longitude));
    }
    return points;
}
